#!/usr/bin/env bash

# Run the container
docker run -p 8080:80 -d -it holbertonschool/265-0

# Get the container ID
CONTAINER_ID=$(docker ps -q -l)

# Install Apache and set up the web page inside the container
docker exec -it "$CONTAINER_ID" bash -c "
  apt-get update &&
  apt-get install -y apache2 &&
  echo 'Hello Holberton' > /var/www/html/index.html &&
  service apache2 start &&
  service apache2 status
"
