#!/usr/bin/env bash
# Install nginx
apt update -y
apt install -y nginx

# Replace port 8080 with 80 in config if needed
sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default

# Start nginx
service nginx start